server.port=8081

# H2 local database
spring.datasource.url=jdbc:h2:file:./data/slmdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORS
spring.web.cors.allowed-origins=http://localhost:5175,http://localhost:5173

spring.application.name=slm-backend
